### ISSUE TITLE
Suggestion: internal brightness and script brightness fix

### ISSUE THREAD

**Issue by gabrielpetersson** [Plippo/screenpad-tools#4]
On my Zenbook pro duo (i9 10th-gen version), some linux patch just seemed to pick up the lightcontrol. Problem is the script provided here and the computer seem to tweak different things, so if either is set to lowest, the screen is black. (still backlit due to IPS screen but no colors) the backlight of the screenpad and `screenpad-tools` are changing different kinds of light. 

`screenpad 9` will set one of these to full, but it might still be pitch black due to the new patch also tweaking with lightning.

The problem is my computer randomly picks either upper screen or lower screen, and I often get stuck on the screenpad getting really dark. Not sure if this is fixable with any additional script but just a heads up if you might know the cause and others experiencing this.

**Comment by Plippo** [comment]
Sorry for not answering earlier! Unfortunately, I have no experience with the Zenbook Pro Duo :( On my "non-Pro" Zenbook, the Kernel's normal brightness control only affects the main screen, I don't even get a backlight device for the ScreenPad. Do you have multiple backlight devices under /sys/class/backlight?

**Comment by gabrielpetersson** [comment]
Hey! Sorry for late response on my side this time. I have the ux581. Seem like brightness-control just released a dual display support, this together with your script enables me to have full brightness. Otherwise I get to max 20% 
`
sudo add-apt-repository ppa:apandada1/brightness-controller
sudo apt update
sudo apt install brightness-controller
`
This file is empty for me `/sys/class/backlight`, but your script still works fine for the below display!

Could add the brightness-controller to README for other pro duo users? Ive tried using only screenpad as main display and changing brightness and all kinds of stuff, nothing else have worked

**Comment by Plippo** [comment]
Good to hear that! If you can write some specifics on how to use brightness-controller, I can add that to the README file. Unfortunately as it doesn't apply to my model, I can't write about it myself.

**Comment by gabrielpetersson** [comment]
You could add: 

For zenbook duo users if this script does not work on its own, you can use it alongside brightness-control. Install with 

```
    sudo add-apt-repository ppa:apandada1/brightness-controller 
    sudo apt update 
    sudo apt install brightness-controller
```

And then the program should pop up in the apps menu. Here you can change brightness of both displays
![image](https://user-images.githubusercontent.com/46445785/104511824-f9217500-55f5-11eb-8954-276211a9e2e0.png)

**Comment by Plippo** [comment]
Thanks for your comment! I've added a link to it to the readme file.

**Comment by gabrielpetersson** [comment]
Cool!

**Comment by gabrielpetersson** [comment]
Made this way back if this is relevant for anyone else using Zenbook pro duo that is coming by this thread, using your rool @Plippo 

https://github.com/gabrielpetersson/asus-zenbook-duo-screenpad-brightness
